services:
  anthropic-proxy:
    image: ll931217/anthropic-proxy:latest
    environment:
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    restart: always

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "5151:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      OLLAMA_BASE_URL: http://192.168.1.126:11434
      DEFAULT_MODELS: claude-3-5-sonnet-20240620
      OPENAI_API_BASE_URL: http://anthropic-proxy:8000/v1
      OPENAI_API_KEY: unused
      WEBUI_AUTH: True
    volumes:
      - open-webui:/app/backend/data
    restart: always
    depends_on:
      - anthropic-proxy

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 300 open-webui

volumes:
  open-webui:
