services:
  anthropic-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    ports:
      - "8000:8000"
    restart: always

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "5000:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DEFAULT_MODELS: claude-3-5-sonnet-20240620
      OPENAI_API_BASE_URL: http://anthropic-proxy:8000/v1
      OPENAI_API_KEY: unused
      WEBUI_AUTH: True
    volumes:
      - open-webui:/app/backend/data
    restart: always
    depends_on:
      - anthropic-proxy

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 300 open-webui

volumes:
  open-webui:
